### ISSUE TITLE
다운로드를 받았을시 폴더안에 아무것도안들어있내요

### ISSUE THREAD

**Issue by qprhvms** [ZHANITEST/Xaru#11]
여러가지 시도해봤는대안되내요;;

그랩으로 시도하면 계속 재시도중만뜨고..

자루는 폴더만 만들어지고 이미지는없내요

**Comment by ZHANITEST** [comment]
저도 뭐라 드릴 말씀이 없네요. 알아서 해결하세요.

만화 제목을 알려주신 것도 아니고 그렇다고 ID를 주신 것도 아니고. 제가 qphvms님이 다운로드 받으신 만화를 추리하면 될까요? 이거 참 어렵군요. 혹시 ID:16의 보쿠걸인가요? 그거 재미없던데.

여튼 안내사항에서 5번 부분에서 말씀드렸듯이 제가 누굴 위해서 버그를 고칠 의무는 없습니다. 고쳐도그만 안고쳐도 그만입니다. 8번부분도 눈여겨 보십시요. 만약 받으시려는 작품이 비밀번호를 입력해야 하는 성인만화라면 '포기' 하십시요.
http://zhanitest.egloos.com/1423154

조금 더 도움을 드리자면 만화 다운로드가 안되는 경우의 이슈 서식이 따로 있는 건 아닙니다만 비슷한 유형의 버그 리포트들을 참조하시어 이슈 글을 작성해주세요.
https://github.com/ZHANITEST/Xaru/issues/10
https://github.com/ZHANITEST/Xaru/issues/2

'어 안된다 빨리 해결부탁!' 하시지 마시고 위와 같이 작성해주신다면 한번 더 읽어는 보겠습니다만 올려주신 이 이슈는 Closed 처리 하겠습니다. 그리고 '없내요'가 아니라 '없네요' 입니다.

즐거운 저녁 되세요. :-)
