### ISSUE TITLE
폴더만 생성되고 다운은 안됩니다

### ISSUE THREAD

**Issue by wodyd971** [ZHANITEST/Xaru#18]
![1](https://cloud.githubusercontent.com/assets/17195074/13003789/ed295818-d1ba-11e5-9ef8-b55a8213eae3.PNG)
![2](https://cloud.githubusercontent.com/assets/17195074/13003791/ed2b3264-d1ba-11e5-8310-5b16b5f0d7e1.PNG)
![3](https://cloud.githubusercontent.com/assets/17195074/13003788/ed287b78-d1ba-11e5-9492-5c74e4c3ffc4.PNG)
![4](https://cloud.githubusercontent.com/assets/17195074/13003793/ed2e8180-d1ba-11e5-80d0-dc9163943bcd.PNG)
![5](https://cloud.githubusercontent.com/assets/17195074/13003792/ed2c4b5e-d1ba-11e5-8a9d-8e18b3f55c2a.PNG)
![6](https://cloud.githubusercontent.com/assets/17195074/13003790/ed2a45de-d1ba-11e5-8b7a-874b1470ab39.PNG)
![7](https://cloud.githubusercontent.com/assets/17195074/13003795/ed4e145a-d1ba-11e5-8e48-7d3c141a0ef9.PNG)
![8](https://cloud.githubusercontent.com/assets/17195074/13003794/ed4dc11c-d1ba-11e5-968b-98e05b707f16.PNG)
![9](https://cloud.githubusercontent.com/assets/17195074/13003796/ed5066ec-d1ba-11e5-86d1-919c26495c5f.PNG)
![10](https://cloud.githubusercontent.com/assets/17195074/13003798/ed508884-d1ba-11e5-80c4-f53ce0e6bc86.PNG)
![11](https://cloud.githubusercontent.com/assets/17195074/13003799/ed51a782-d1ba-11e5-959f-dff2247fb305.PNG)
![12](https://cloud.githubusercontent.com/assets/17195074/13003797/ed5081ea-d1ba-11e5-985b-f6afe487eef8.PNG)
![13](https://cloud.githubusercontent.com/assets/17195074/13003802/ed732290-d1ba-11e5-974d-f914ab98df2d.PNG)
![14](https://cloud.githubusercontent.com/assets/17195074/13003801/ed71083e-d1ba-11e5-9514-2baa5e117e98.PNG)

상황이 어떤지 찍어보았습니다
현재 다운로드를 받을시 폴더만생성되고 안에는 비어있는상황이 생깁니다
zip롤 압축옵션을 선택해도 똑같네요

**Comment by ZHANITEST** [comment]
매우매우 자세한 이슈 내용 감사합니다. ^^
프로그램 버그로 확인되었고 0.08버전에 적용하여 공개하겠습니다.

즐거운 연휴 되세요. :-)

**Comment by ZHANITEST** [comment]
좋으시든 싫으시든, 0.08버전에서 반영되어 배포중입니다.

http://zhanitest.egloos.com/1423154

감사합니다. :-)

**Comment by wodyd971** [comment]
제가 고맙죠 뭐
