### ISSUE TITLE
다운로드가 안돼요

### ISSUE THREAD

**Issue by ryul99** [ZHANITEST/Xaru#2]
주문은 토끼입니까?를 다운받는데 이전분과 비슷한 오류가 뜨네요...
아마도 폴더에 ?가 들어갈 수 없어서 뜨는 오류같은데 부탁드립니다...ㅎㅎ

**Comment by ZHANITEST** [comment]
yee런... 일단 코드 상의 문제는 맞습니다. 너무 안이하게 생각한 제 탓입니다. 죄송합니다... 지금 버그는 수정되었고 아직 커밋과 릴리즈 빌드는 못했습니다. 급하게 나가봐야 해서...

오후 2시쯤에 제 블로그에(http://zhanitest.egloos.com/1423154) "0.5버전"이 올라와있을 것입니다.
번거로우시겠지만 확인 부탁드립니다. 감사합니다. ^^
