### ISSUE TITLE
다운로드 오류

### ISSUE THREAD

**Issue by wodyd971** [ZHANITEST/Xaru#23]
![default](https://cloud.githubusercontent.com/assets/17195074/13916152/44b449f4-ef9c-11e5-9697-a92b5a56eac9.PNG)
![2](https://cloud.githubusercontent.com/assets/17195074/13916311/31c37a80-ef9d-11e5-9290-a640a3980fba.PNG)

왜이려죠 이거

**Comment by ZHANITEST** [comment]
오늘이나 내일 중으로 검토해보겠습니다.

**Comment by ZHANITEST** [comment]
프로그램 버그는 아니고, 마루마루 사이트가 닫혀 있으면(예를 들면 디도스 공격 및 사이트 다운) URL리스트생성에 실패하게 됩니다. 이 프로그램은 마루마루 사이트를 읽어오는 것을 기초로 처리하기 때문에 사이트에서 읽어오는 걸 실패해서 발생한 에러 메세지 같습니다. 다시 한번 시도해보시길 바랍니다. :-)
