### ISSUE TITLE
오류..? 

### ISSUE THREAD

**Issue by Powa12** [ZHANITEST/Xaru#24]
![dfdf](https://cloud.githubusercontent.com/assets/18610609/14735067/bc6746ce-08a9-11e6-96d5-6469358378a3.JPG)
뭘까요 이게..?

**Comment by ZHANITEST** [comment]
오늘이나 내일 안으로 확인해보겠습니다만,
에러 보고 시에 다운받으려고 하셨던 "작품 코드"나 "카테고리 순서"를 입력해주시면 버그를 고치는데 더욱 도움이 됩니다.

**Comment by ZHANITEST** [comment]
보아하니 만화명은 '신화 펀치' 인 것 같습니다.
카테고리 다운로드의 문제같은데, 일단 ID 입력 시 0.12버전 기준으로 잘 동작하니 참고하시길 바랍니다...

만화명: 신화 펀치
ID: 134961
스크린샷:
![preview](https://cloud.githubusercontent.com/assets/6543940/17125051/35703e4c-532b-11e6-9717-d4b783f61e20.png)

XaruGUI 0.12버전: http://zhanitest.egloos.com/1438768
