### ISSUE TITLE
이미지 완전하게 다운로드가 안되요

### ISSUE THREAD

**Issue by mrsimple97** [ZHANITEST/Xaru#25]
![image](https://cloud.githubusercontent.com/assets/18537498/17834406/f7b2ce5e-6779-11e6-93c3-59d5675a1220.png)

이런식으로 파일이 깨지네요. 만화 이름은 니세코이이구요, 188화부터 저러네요

**Comment by ZHANITEST** [comment]
해당 문제는 마루마루 서버측의 문제로 보여집니다. 2016-08-27일자로 189화를 다운로드를 시도해보니 잘 받아집니다.... 믿기어려우실 것 같아서 아래 정상으로 다운로드 된 파일의 스크린샷을 첨부하여 드립니다.

![default](https://cloud.githubusercontent.com/assets/6543940/18027570/7172eb02-6ca2-11e6-8d81-6b5c040cd358.png)
