### ISSUE TITLE
만화 검색시 오류가 발생 합니다.

### ISSUE THREAD

**Issue by MarsK0013** [ZHANITEST/Xaru#27]
만화 제목 : 네지마키 카규
주소 : http://marumaru.in/b/manga/11
검색 탭에서 네지마키 카규 검색시 오류가 발생 합니다.
그리고 다운로드 탭에서 카테고리로 검색시 완결 목록에 나오지가 않습니다.
위 URL로 검색시에도 동일한 오류가 발생합니다.
구동 OS 는 Windows 10 x64 입니다.
![default](https://cloud.githubusercontent.com/assets/22513104/18940318/19d0421e-8642-11e6-9a26-564e28f72744.JPG)
![01](https://cloud.githubusercontent.com/assets/22513104/18940420/fddcfc4a-8642-11e6-8713-da4180dcad39.JPG)

**Comment by ZHANITEST** [comment]
Xaru.d 내부의 버그로 판단됩니다.
이슈 보내주셔서 감사합니다!

**Comment by ZHANITEST** [comment]
59a9420f98adf6027a040647dfffd01ad1ccc553

해결 완료.
