### ISSUE TITLE
파일명 개선부탁...

### ISSUE THREAD

**Issue by ryul99** [ZHANITEST/Xaru#3]
항상 잘 쓰고 있습니다ㅎ
되는 다운로더가 이거밖에 없는 것같아요ㅋㅋㅋ
다만 다운받을때 1,2,3...으로 되면 파일명순으로 정렬하면 0,11,12,...,1,21,22...로 되더라고요...
혹시나 처음 10개를 0,01,02,...,09로 저장되게 해주실 수 있나요??

**Comment by ZHANITEST** [comment]
안녕하세요. ^^
어려운 일은 아닌데 기본 기능으로 넣을 지 아니면 옵션으로 선택 가능하게 할 지 고민좀 해보고 바로 반영하겠습니다. 감사합니다. :-)

**Comment by ryul99** [comment]
네ㅎㅎ감사합니다

**Comment by ZHANITEST** [comment]
많이 부족하지만 일단 필요하신 기능을 넣은 0.06 릴리즈 했습니다.
http://zhanitest.egloos.com/1423154
감사합니다. :-)

**Comment by ryul99** [comment]
ㅎㅎㅎ이미 오늘 새벽에 써봤어요ㅎㅎ
항상 감사합니다ㅋㅋㅋ
