### ISSUE TITLE
135460(중간관리록 토네가와) 검색할때 오류납니다.

### ISSUE THREAD

**Issue by aifirst** [ZHANITEST/Xaru#32]
![xaru-gui](https://cloud.githubusercontent.com/assets/20848552/21294507/9092ae86-c581-11e6-8969-709b863cbc5a.png)

만화번호: 135460
만화제목: 중간관리록 토네가와

수고하십시오.

**Comment by ZHANITEST** [comment]
안녕하세요,
버그로 판단되어 라벨 변경했습니다. 제보 감사합니다.  😸
