### ISSUE TITLE
버그 리포터 입니다

### ISSUE THREAD

**Issue by ytoaa** [ZHANITEST/Xaru#35]
만화id: 136657
만화제목: 어째서 여기에 선생님이!_(골든 타임즈)
회차: 전체
![image](https://cloud.githubusercontent.com/assets/24527825/21752205/a8c7c44a-d617-11e6-8fba-07844396f69b.png)

**Comment by ZHANITEST** [comment]
아무래도 '에필로그' 편에 암호가 잠겨서 그런 듯 합니다만...

**Comment by ZHANITEST** [comment]
비밀번호가 잠긴 회차 '에필로그 편' 빼고 다운로드 가능합니다.
비밀번호가 걸린 페이지의 경우 아직까지 다운로드 불가능 하니 참고해주시길 바랍니다.
http://xaruxaru.96.lt/doku.php?id=helpdoc#%EC%9D%BC%EB%B6%80_%EC%84%B1%EC%9D%B8%EB%A7%8C%ED%99%94%EC%9D%98_%EA%B2%BD%EC%9A%B0

**Comment by ZHANITEST** [comment]
0.23버전부터 암호가 걸린 만화로 다운로드 받을 수 있도록 할 '계획' 입니다. 참고하시길 바랍니다. 😄

**Comment by ZHANITEST** [comment]
0.27버전에서 해결되었습니다.
