### ISSUE TITLE
다운로드 오류

### ISSUE THREAD

**Issue by wodyd971** [ZHANITEST/Xaru#36]
![1](https://cloud.githubusercontent.com/assets/17195074/21792470/6c6d8ab8-d72d-11e6-888d-2f5724d13171.PNG)
![2](https://cloud.githubusercontent.com/assets/17195074/21792471/6c7b1048-d72d-11e6-9b52-eeb2cef97838.PNG)

**Comment by ZHANITEST** [comment]
이거 xaru.d 로컬 상에는 문제해결 했는데 아직 git 레퍼지토리에 반영도 안했고 xaru-gui 새 버전으로 빌드를 안해서 그래요. 반영 후에 이슈 닫겠습니다.

**Comment by wodyd971** [comment]
어...제가 잘못한건가영...?

**Comment by ZHANITEST** [comment]
경쟁전끝나고자세히댓글달아드리겠숩니당ㅋㅋㅋ 프로그램 0.19 업데이트 되었으니 확인 부탁드립니다!
시메트라 넘나 센것...
