### ISSUE TITLE
주소로 인한 오류

### ISSUE THREAD

**Issue by Satki** [ZHANITEST/Xaru#37]
![default](https://cloud.githubusercontent.com/assets/25026240/21796765/2e14b3a6-d74e-11e6-8309-35124e3fd988.jpg)

사이케 또다시( ID : 53064 ) 47~52화 다운시 오류.

이게 직접가서 주소를 보니 www.yun~ 이아니라 blog.yun~로 되어있어서 생기는 문제같네요.

아래이슈에있는 어째서 선생님이 응딩이편도 blog.yun~ 으로 되어있어서 확인해봤는데 동일한 오류확인했습니다.

**Comment by Satki** [comment]
0.18일때 확인했었는데 0.19에선 되는군요. 벌써 수정하신듯
근데 이거 삭제버튼이 안보여서 못내리네요!

**Comment by ZHANITEST** [comment]
close 단추는 개발자가 누르게 되어 있습니다.ㅋㅋ
아무튼 제보해주셔서 감사합니다 ~~ 😸
