### ISSUE TITLE
다운로드 오류

### ISSUE THREAD

**Issue by YenOnY** [ZHANITEST/Xaru#38]
안녕하세요 우연히 프로그램을 발견하여 유용하게 잘쓰던 중에 다운로드 오류가 발생하여 문의드립니다.

1)
만화 제목: 내 첫사랑을 너에게 바친다
ID: 183426
회차: 전체
오류 내용: 만화의 이미지파일 주소를 찾는데 실패했습니다 

2)
만화 제목: 열정 C 맥스
ID: 185269
회차: 전체
오류 내용: 만화의 이미지파일 주소를 찾는데 실패했습니다

**Comment by ZHANITEST** [comment]
버그 문의 주셔서 감사합니다. 검토해서 수정하도록 하겠습니다.

즐거운 설 명절 보내세요~ 😁

**Comment by ZHANITEST** [comment]
해결된 지 꽤 됬는데 답변을 못드렸네요! 17-05-09 날짜로 0.22 r1 기준 정상동작합니다! 😄
