### ISSUE TITLE
문제제기

### ISSUE THREAD

**Issue by yiminsoo** [ZHANITEST/Xaru#47]
ID: <만화ID> → 16 , 63241
품명: <만화제목> → 보쿠걸, 니세코이
회차: <받으려고 했던 만화의 회차> → 목록생성 불가
에러: <에러 메세지 내용> → 본문에서 만화주소 (범위)를 읽는데 실패했습니다.

**Comment by ZHANITEST** [comment]
안녕하세요 😄 

혹시 몇버전이 말씀해주실 수 있으신가요?

**Comment by wmdmf2003** [comment]
0.21, 0.22 버전에서 모두 동일한 오류가 발생하며, 어떤 ID를 입력하더라도 같은 오류가 뜹니다. 
심지어 1234567890등의 ID를 입력해도 동일한 오류가 뜨는 걸로 봐서는, 배포판에서 어떤 라이브러리가 누락된 것은 아닐까 싶은데요.
D언어는 모르지만 소스도 한번 살펴봤는데, 해당 오류메세지(본문에서 만화주소 (범위)를 읽는데 실패했습니다.)로 안내하는 구문이 안보여서 참고가 안 되겠군요.
0.20 버전은 제대로 동작합니다.

Windows 10 64bit 10.0.14393

**Comment by ZHANITEST** [comment]
HTML 사이트 구조가 변경된 것 같기도 하네요. 자세한 건 좀 뜯어봐야 알 듯 싶습니다.
우선적으로 검토해서 고치도록 하겠습니다  😁

**Comment by ZHANITEST** [comment]
1. XARU 0.22기준 17-05-09 테스트 해보니 두 항목(16, 63241)모두 ID를 읽어오는데 문제가 없었습니다.
추정 상으로는 마루마루 홈페이지의 사이트가 잠시 다운되었거나 하는 문제로 프로그램 상에서 읽어오지 못했으리라 추정됩니다.

2. 아직 0.22의 코드를 레퍼지토리에 커밋을 못해서 최신버전과의 코드는 좀 상이할 수 있습니다. 업데이트 해두겠습니다.

사이트가 다운되었는 지도 확인하는 구문이 추가적으로 프로그램 상에서도 필요하겠네요.
비슷한 사례로 몇번 이슈를 받은 적이 있었으니...

#30 의 WIP항목 6번으로 추가하였습니다. 감사합니다. 😃

**Comment by ZHANITEST** [comment]
0.27 기준 해결되었습니다.
