### ISSUE TITLE
버그신고

### ISSUE THREAD

**Issue by aifirst** [ZHANITEST/Xaru#48]
ID: 116173 
품명: 주문은 토끼입니까?
회차: 전체
에러:
std.windows.syserror.WindowsException@C:\D\dmd2\windows\bin\..\..\src\phobos\std\file.d(2163): download/주문은 토끼입니까(116173)/주문은 토끼입니까? 1-7화/: 파 일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다. (error 123)
----------------
0x00411A5B
0x0040E67A
0x0040F75F

언언제제나나 감감사사드드립립니니다다..

**Comment by ZHANITEST** [comment]
Yee런.. 저번에 해결한 이슈인데 다시 발생했군요.
라벨을 버그(:bug: )로 붙였습니다. 차기 버전에서 해결하도록 하겠습니다. :smile:

**Comment by ZHANITEST** [comment]
#47 와 비슷한 상황으로 추정됩니다. 이 역시 17-05-09날짜로 0.22 r1으로 테스트해본 결과 정상동작합니다! 😃

**Comment by ZHANITEST** [comment]
https://github.com/ZHANITEST/Xaru/commit/93184f7d42a9fb621ca86ced4b0341d96493d02a

🐛 되살아남 🐛

**Comment by ZHANITEST** [comment]
0.27버전에서 해결되었습니다.
