### ISSUE TITLE
xaru 0.22 오류입니다.

### ISSUE THREAD

**Issue by edsdream** [ZHANITEST/Xaru#49]
ID: 2966
품명: 리브니스
회차: 46화
에러: 

PS D:\Download\bin_022AR1> .\xaru.exe
 [ xaru.d ] v0.22A r1 / Copyleft 2017 zhanitest(.egloos.com) / LGPL v2
xaru.d / ID입력 >>> 2966

object.Exception@source\app.d(505): 본문에서 만화주소 부분의 위치(범위)를 읽는데 실패했습니다.
----------------
0x00405F69
0x0040F4B7
0x004C28CF
0x004C27D0
0x004424F0
0x74328744 in BaseThreadInitThunk
0x7761587D in RtlGetAppContainerNamedObjectPath
0x7761584D in RtlGetAppContainerNamedObjectPath

현재 사용중인 os는 win10 pro rs2 64bit입니다.
해당 만화는 xaru-gui 0.19버전에서는 이상없이 다운로드되었습니다.

**Comment by ZHANITEST** [comment]
버그라벨로 붙였습니다. 제보해주셔서 감사합니다. :smile:

**Comment by ZHANITEST** [comment]
#47와 비슷한 상황으로 추정됩니다. 17-05-09날짜로 XARU 0.22로 테스트해보니 정상동작합니다.
감사합니다. 😃

**Comment by ZHANITEST** [comment]
다시 버그로 오픈했습니다. :beetle:

**Comment by ZHANITEST** [comment]
0.27버전에서 해결되었습니다.
