### ISSUE TITLE
 더 이상 유지보수를 할 필요가 있을까

### ISSUE THREAD

**Issue by ZHANITEST** [ZHANITEST/Xaru#50]
http://zhanitest.egloos.com/1450170

예상은 했으나 좀 심각하게 딜레마에 빠짐.

**Comment by DPain** [comment]
고생이다. =_=

**Comment by ZHANITEST** [comment]
@DPain 솔직히 내 시간 쪼개가면서 유지보수하는데, 일침 같은 거 들으면 아무리 사실이라고 해도 맥 빠지긴 하지. 어쩔 수 음슴
