### ISSUE TITLE
윈10이라 그런지 모르겟는데

### ISSUE THREAD

**Issue by wodyd971** [ZHANITEST/Xaru#54]
쉬프트 우클릭시 명령창 대신 파워셀(windows powershell) 기능이 나오네요
이거 어떻게 수정하지..?

**Comment by ZHANITEST** [comment]
Windows 10이랑은 관계가 없는 것 같습니다. 제가 그렇게 사용하고 있고...
구글에 한번 검색해보시고, 정 안되시면 그냥 xaru.exe를 더블클릭 하셔도 됩니다.

해결되신 경우에는 이슈 닫아주세요 :smile_cat:

**Comment by ZHANITEST** [comment]
+++ 수정 +++
Windows10을 최신으로 업데이트 하니 저도 명령창 대신 Powershell 창이 나오는군요. 😅 
그런 경우 `cmd`라고 입력하신 후에 `xaru`를 입력해주시면 됩니다.

**Comment by ZHANITEST** [comment]
해결되신 것으로 판단하고 이슈 닫겠습니다~
