### ISSUE TITLE
프로그램 시작할 때 입력변수로 회차 인덱스도 받는 건 어떨까요?

### ISSUE THREAD

**Issue by HideOnHouse** [ZHANITEST/Xaru#58]
크롬 북마크를 html로 내보내서 id만 뽑아온 후  "xaru.exe id"까지는 되는데 인덱스를 입력 인자로 받지 않아 일일히 입력해야하는게 조금 아쉽네요..

북마크 html 던져주면 자동으로 전부 받아오는 파이썬 프로그램을 만들고 있습니다.

**Comment by ZHANITEST** [comment]
좋은 아이디어 같습니다..
커맨드 프로그램이긴 한데 생각보다 '커맨드'가 많이 약했던 것 같네요..

good idea 라벨 붙였습니다. 의견 감사합니다. 😺

**Comment by ZHANITEST** [comment]
혹시 만드신 repository 중에

https://github.com/fffuro/Python-Stuff/blob/master/idext.py

요거랑 관련이 있나요??

**Comment by HideOnHouse** [comment]
맞습니다. 북마크 내보낸거 정리하는 bookparse.py하고, xaru에서 쓰기 위한 idext.py하고, 그걸 자동으로 하기 위한 auto.py, 예전 폴더 이름을 현재 폴더 이름으로  정리하는 rename.py로 구성되어있습니다.

**Comment by ZHANITEST** [comment]
@fffuro 알겠습니다~ 커맨드 입력 기능을 기존에는 ID만 가능한데 INDEX까지 가능하게 하겠습니다.
아래와 같은 스타일로,

```xaru <ID>```
```xaru -id <ID>```
```xaru -idx <INDEX>```

적용해볼까 하는데 괜찮은지요?
기존에 xaru id 로 쓰시는 분들은 혼동이 없게 하고 싶은데..

**Comment by HideOnHouse** [comment]
감사합니다!
xaru -idx <INDEX>면 xaru -idx [id] [index] 라는 말슴이시죠?

**Comment by ZHANITEST** [comment]
```
xaru <ID만 입력>
xaru -id <ID만 입력>
xaru -idx <INDEX만 입력>
```

이었습니다. ID와 INDEX가 서로 상관이 없는 경우(ex. A라는 작품의 ID와 B라는 작품의 INDEX) 혼동이 생길 것 같습니다.

ID를 입력하면 INDEX를 선택하는 화면을 보여주고(기존과 동일합니다), INDEX를 입력하면 그냥 그 회차를 다운로드 할 있도록 할 예정입니다.

**Comment by ZHANITEST** [comment]
7a538db에서 해당 내용 반영했습니다.

```
xaru <ID만 입력>
xaru -id <ID만 입력>
xaru -idx <INDEX만 입력>
```

원래 계획은 위와 같이 사용하는 거였는데, 굳이 -id는 필요 없을 것 같아서

```
xaru <ID만 입력>
xaru -idx <INDEX만 입력>
```

위와 같이 사용할 수 있도록 적용했습니다. 🤓
