### ISSUE TITLE
18년 6월 18일 기준 막힙니다

### ISSUE THREAD

**Issue by wodyd971** [ZHANITEST/Xaru#61]
29버전은 다운은 되는데 파일이 읽히지 않고 28버전은 아예 다운자체가 안되네요

**Comment by ZHANITEST** [comment]
안녕하세요 :-)

최근 제 업무도 바뀌고(...) 주말엔 연수도 다니다보니 취미프로젝트에 신경을 쓸 시간이 많이 없어졌습니다.

일단 지금의 소스코드로는 문제를 해결하기 어렵다고 판단해서 테스트 툴부터 다시 작성할 예정이구요.

다시 릴리즈 할 때까지는 기다려주셔야 될 것같습니다.

.. 오늘은 축구라도 보시는 게 어떠실까요 :-)

**Comment by wodyd971** [comment]
아 죄송합니다 바쁘신중에...

**Comment by ZHANITEST** [comment]
오늘 새벽 축구는 꼭 이겼으면 좋겠네요 ⚽️ 

xaru는 제 취미플젝 중엔 그래도 길게 유지보수 해온 터라 애착도 있고해서
개발이 아예 멈춰지진 않을 겁니다.

느리지만 하나씩 수정해나갈 예정이구요. 나름 앞으로의 모델도 고민하고 있습니다.
블록체인 위에 올릴 생각도 해보고 있어요. :-)

**Comment by ZHANITEST** [comment]
만화 서치/다운로드 기능 관련 버그를 수정한 버전입니다. Windows에서 Powershell에서 실행 시 한글출력 문제가 있으나, 다운로드는 잘 되네요.
그냥 *로 다운로드 받으시는데 문제 없을 겁니다... 😅 

### 0.30 Version - Alpha(debug)

  - 여기: http://zhanitest.egloos.com/1465898
  - 혹은 직접 다운로드: http://pds21.egloos.com/pds/201807/14/78/xaru_030A(D).zip

기타문의사항은 discord 채널에서 도와드리겠습니다:
  - https://discord.gg/GgVeVFt

**Comment by ZHANITEST** [comment]
- https://github.com/ZHANITEST/Xaru/commit/85d91ba0d0f636d6a71adeaac52f370d670c8133 커밋 이후로 말씀하신 내용은 정상 동작합니다만,  한글출력에 문제가 있습니다.
  - 우선 이 이슈를 닫고 한글출력 이슈를 추가하였으니 참고바랍니다: https://github.com/ZHANITEST/Xaru/issues/62

감사합니다.
