### ISSUE TITLE
파일 일괄 압축기능

### ISSUE THREAD

**Issue by ZHANITEST** [ZHANITEST/Xaru#7]
스마트폰에서도 볼 때 옮기기 쉽게 다운로드 받은 파일들을 ZIP으로 압축하는 기능 추가 예정.!

**Comment by ryul99** [comment]
오오 이거 좋을것같네요ㅎ
근데...가끔 한번에 많이 받으면 오류나던데 지금은 추가적으로 더 받으면 되지만 zip으로 압축하면...
이점도 고려해주세요ㅎㅎㅎ

**Comment by ZHANITEST** [comment]
PhantomJS가 웹페이지를 읽어오는데 걸리는 timeout 값이 좀 짧아서 그런 것 같습니다. 스크립트를 고치면 해결될 것 같긴한데... 일단 이번 커밋에서 기존 시간에 3배로 늘렸습니다. :P https://github.com/ZHANITEST/Xaru/commit/640ecb0cd58c913248d4eabdf9816d4bf1088efd

**Comment by ZHANITEST** [comment]
혹시 말씀하신 오류 좀 자세히 알려주실 수 있으신지?
에러 메세지 목격하시면 이슈 부탁드려요. :-)

**Comment by ZHANITEST** [comment]
https://github.com/ZHANITEST/Xaru/commit/9afa068f2b04e2858da8e19d08baeb3ab4c9f740

ZIP 압추기능 추가!

**Comment by ryul99** [comment]
이슈를 어떻게 남기는지 몰라서...메일로 보냅니다ㅎ
가끔 시간초과되면 이런 오류메세지가 뜨네요ㅎ

**Comment by ZHANITEST** [comment]
오류 메세지 첨부 부탁드려요~
이미지 캡쳐나 PrtScreen으로 찍어 보내주셔도 되요.

**Comment by ryul99** [comment]
항상감사합니다...ㅎ
보이시나요...???

**Comment by ZHANITEST** [comment]
아니요.. 여전히 안보이네요. 번거로우시겠지만 이메일로 첨부 부탁드립니다..
mozirikan-AT-gmail-DOT-com
